// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "Main", "symbols": ["formatOne"]},
    {"name": "Main$subexpression$1", "symbols": ["float"]},
    {"name": "Main$subexpression$1", "symbols": ["int"]},
    {"name": "Main$subexpression$1", "symbols": ["formatOne"]},
    {"name": "Main$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "Main$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Main", "symbols": ["range", "_", "Main$subexpression$1", "Main$ebnf$1", "range", "_", "formatOne"]},
    {"name": "Main", "symbols": ["noCurrency"]},
    {"name": "Main", "symbols": ["formatTwo"]},
    {"name": "Main", "symbols": ["scalars"]},
    {"name": "Main", "symbols": ["currency"]},
    {"name": "Main", "symbols": ["time"]},
    {"name": "float$subexpression$1", "symbols": [{"literal":"."}]},
    {"name": "float$subexpression$1", "symbols": [{"literal":","}]},
    {"name": "float", "symbols": ["int", "float$subexpression$1", "int"], "postprocess": function(d) {return {token:"number",value:parseFloat(d[0].value + "." + d[2].value)}}},
    {"name": "float$subexpression$2", "symbols": [{"literal":"."}]},
    {"name": "float$subexpression$2", "symbols": [{"literal":","}]},
    {"name": "float", "symbols": ["int", "_", "int", "float$subexpression$2", "int"], "postprocess": function(d) {return {token:"number",value:parseFloat(d[0].value + d[2].value + "." +d[4].value )}}},
    {"name": "int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$1", "symbols": ["int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "int", "symbols": ["int$ebnf$1"], "postprocess": function(d) {return {token:"number",value:d[0].join("")}}},
    {"name": "range$subexpression$1$string$1", "symbols": [{"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$1"]},
    {"name": "range$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$2"]},
    {"name": "range$subexpression$1$string$3", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$3"]},
    {"name": "range$subexpression$1$string$4", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$4"]},
    {"name": "range$subexpression$1$string$5", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$5"]},
    {"name": "range$subexpression$1$string$6", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"x"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$6"]},
    {"name": "range$subexpression$1$string$7", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":"j"}, {"literal":" "}, {"literal":"n"}, {"literal":"i"}, {"literal":"ż"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$7"]},
    {"name": "range$subexpression$1$string$8", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"ę"}, {"literal":"c"}, {"literal":"e"}, {"literal":"j"}, {"literal":" "}, {"literal":"n"}, {"literal":"i"}, {"literal":"ż"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "range$subexpression$1", "symbols": ["range$subexpression$1$string$8"]},
    {"name": "range", "symbols": ["range$subexpression$1"], "postprocess": function(d) {return {token:"range", value:d[0][0]}}},
    {"name": "scalars$subexpression$1$string$1", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$1"]},
    {"name": "scalars$subexpression$1$string$2", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"d"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$2"]},
    {"name": "scalars$subexpression$1$string$3", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"d"}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$3"]},
    {"name": "scalars$subexpression$1$string$4", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ą"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$4"]},
    {"name": "scalars$subexpression$1$string$5", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ą"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$5"]},
    {"name": "scalars$subexpression$1$string$6", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ę"}, {"literal":"c"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$6"]},
    {"name": "scalars$subexpression$1$string$7", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$7"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"k"}]},
    {"name": "scalars$subexpression$1$string$8", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"ś"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$8"]},
    {"name": "scalars$subexpression$1$string$9", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$9"]},
    {"name": "scalars$subexpression$1$string$10", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$10"]},
    {"name": "scalars$subexpression$1$string$11", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$11"]},
    {"name": "scalars$subexpression$1$string$12", "symbols": [{"literal":"m"}, {"literal":"l"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$12"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"M"}]},
    {"name": "scalars$subexpression$1$string$13", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$13"]},
    {"name": "scalars$subexpression$1$string$14", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$14"]},
    {"name": "scalars$subexpression$1$string$15", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$15"]},
    {"name": "scalars$subexpression$1$string$16", "symbols": [{"literal":"m"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$16"]},
    {"name": "scalars$subexpression$1$string$17", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$17"]},
    {"name": "scalars$subexpression$1$string$18", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$18"]},
    {"name": "scalars$subexpression$1$string$19", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$19"]},
    {"name": "scalars$subexpression$1$string$20", "symbols": [{"literal":"b"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$20"]},
    {"name": "scalars$subexpression$1$string$21", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$21"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"%"}]},
    {"name": "scalars$subexpression$1$string$22", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$22"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"‰"}]},
    {"name": "scalars$subexpression$1$string$23", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"o"}, {"literal":"ń"}, {"literal":"c"}, {"literal":"z"}, {"literal":"o"}, {"literal":"n"}, {"literal":"o"}, {"literal":"ś"}, {"literal":"ć"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$23"]},
    {"name": "scalars$subexpression$1$string$24", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"z"}, {"literal":" "}, {"literal":"o"}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"c"}, {"literal":"z"}, {"literal":"e"}, {"literal":"ń"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$24"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"∞"}]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"x"}]},
    {"name": "scalars$subexpression$1$string$25", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"z"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"o"}, {"literal":"ś"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$25"]},
    {"name": "scalars$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "scalars$subexpression$1$string$26", "symbols": [{"literal":"n"}, {"literal":"/"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$26"]},
    {"name": "scalars$subexpression$1$string$27", "symbols": [{"literal":"b"}, {"literal":"."}, {"literal":"d"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$27"]},
    {"name": "scalars$subexpression$1$string$28", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$28"]},
    {"name": "scalars$subexpression$1$string$29", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$29"]},
    {"name": "scalars$subexpression$1$string$30", "symbols": [{"literal":"b"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$30"]},
    {"name": "scalars$subexpression$1$string$31", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"j"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "scalars$subexpression$1", "symbols": ["scalars$subexpression$1$string$31"]},
    {"name": "scalars", "symbols": ["scalars$subexpression$1"], "postprocess": function(d) {return {token:"scalar", value:d[0][0]}}},
    {"name": "time$subexpression$1$string$1", "symbols": [{"literal":"d"}, {"literal":"z"}, {"literal":"i"}, {"literal":"e"}, {"literal":"ń"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$1"]},
    {"name": "time$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"n"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$2"]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"d"}]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"D"}]},
    {"name": "time$subexpression$1$string$3", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"d"}, {"literal":"z"}, {"literal":"i"}, {"literal":"e"}, {"literal":"ń"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$3"]},
    {"name": "time$subexpression$1$string$4", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"g"}, {"literal":"o"}, {"literal":"d"}, {"literal":"n"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$4"]},
    {"name": "time$subexpression$1$string$5", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"g"}, {"literal":"o"}, {"literal":"d"}, {"literal":"n"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$5"]},
    {"name": "time$subexpression$1$string$6", "symbols": [{"literal":"t"}, {"literal":"y"}, {"literal":"d"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$6"]},
    {"name": "time$subexpression$1$string$7", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ą"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$7"]},
    {"name": "time$subexpression$1$string$8", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ą"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$8"]},
    {"name": "time$subexpression$1$string$9", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"ę"}, {"literal":"c"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$9"]},
    {"name": "time$subexpression$1$string$10", "symbols": [{"literal":"m"}, {"literal":"-"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$10"]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"M"}]},
    {"name": "time$subexpression$1$string$11", "symbols": [{"literal":"m"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$11"]},
    {"name": "time$subexpression$1$string$12", "symbols": [{"literal":"k"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"ł"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$12"]},
    {"name": "time$subexpression$1$string$13", "symbols": [{"literal":"k"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"ł"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$13"]},
    {"name": "time$subexpression$1$string$14", "symbols": [{"literal":"k"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"ł"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$14"]},
    {"name": "time$subexpression$1$string$15", "symbols": [{"literal":"k"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$15"]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"Q"}]},
    {"name": "time$subexpression$1$string$16", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$16"]},
    {"name": "time$subexpression$1$string$17", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$17"]},
    {"name": "time$subexpression$1$string$18", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "time$subexpression$1", "symbols": ["time$subexpression$1$string$18"]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"r"}]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"R"}]},
    {"name": "time$subexpression$1", "symbols": [{"literal":"Y"}]},
    {"name": "time", "symbols": ["time$subexpression$1"], "postprocess": function(d) {return {token:"time", value:d[0][0]}}},
    {"name": "currency$subexpression$1$string$1", "symbols": [{"literal":"A"}, {"literal":"U"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$1"]},
    {"name": "currency$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$2"]},
    {"name": "currency$subexpression$1$string$3", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$3"]},
    {"name": "currency$subexpression$1$string$4", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"ó"}, {"literal":"w"}, {"literal":" "}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1$string$5", "symbols": [{"literal":"E"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$4", "currency$subexpression$1$string$5"]},
    {"name": "currency$subexpression$1$string$6", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$6"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"€"}]},
    {"name": "currency$subexpression$1$string$7", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$7"]},
    {"name": "currency$subexpression$1$string$8", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"k"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$8"]},
    {"name": "currency$subexpression$1$string$9", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"k"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$9"]},
    {"name": "currency$subexpression$1$string$10", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"ó"}, {"literal":"w"}, {"literal":" "}, {"literal":"k"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}, {"literal":"j"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$10"]},
    {"name": "currency$subexpression$1$string$11", "symbols": [{"literal":"C"}, {"literal":"N"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$11"]},
    {"name": "currency$subexpression$1$string$12", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$12"]},
    {"name": "currency$subexpression$1$string$13", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$13"]},
    {"name": "currency$subexpression$1$string$14", "symbols": [{"literal":"j"}, {"literal":"u"}, {"literal":"a"}, {"literal":"n"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$14"]},
    {"name": "currency$subexpression$1$string$15", "symbols": [{"literal":"H"}, {"literal":"R"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$15"]},
    {"name": "currency$subexpression$1$string$16", "symbols": [{"literal":"k"}, {"literal":"u"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$16"]},
    {"name": "currency$subexpression$1$string$17", "symbols": [{"literal":"k"}, {"literal":"u"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$17"]},
    {"name": "currency$subexpression$1$string$18", "symbols": [{"literal":"C"}, {"literal":"Z"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$18"]},
    {"name": "currency$subexpression$1$string$19", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"z"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$19"]},
    {"name": "currency$subexpression$1$string$20", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"c"}, {"literal":"z"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$20"]},
    {"name": "currency$subexpression$1$string$21", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"c"}, {"literal":"z"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$21"]},
    {"name": "currency$subexpression$1$string$22", "symbols": [{"literal":"D"}, {"literal":"K"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$22"]},
    {"name": "currency$subexpression$1$string$23", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"ń"}, {"literal":"s"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$23"]},
    {"name": "currency$subexpression$1$string$24", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"ń"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$24"]},
    {"name": "currency$subexpression$1$string$25", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"ń"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$25"]},
    {"name": "currency$subexpression$1$string$26", "symbols": [{"literal":"E"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$26"]},
    {"name": "currency$subexpression$1$string$27", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$27"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"€"}]},
    {"name": "currency$subexpression$1$string$28", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$28"]},
    {"name": "currency$subexpression$1$string$29", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$29"]},
    {"name": "currency$subexpression$1$string$30", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$30"]},
    {"name": "currency$subexpression$1$string$31", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$31"]},
    {"name": "currency$subexpression$1$string$32", "symbols": [{"literal":"E"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$32"]},
    {"name": "currency$subexpression$1$string$33", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$33"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"€"}]},
    {"name": "currency$subexpression$1$string$34", "symbols": [{"literal":"J"}, {"literal":"P"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$34"]},
    {"name": "currency$subexpression$1$string$35", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$35"]},
    {"name": "currency$subexpression$1$string$36", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$36"]},
    {"name": "currency$subexpression$1$string$37", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"n"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$37"]},
    {"name": "currency$subexpression$1$string$38", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$38"]},
    {"name": "currency$subexpression$1$string$39", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$39"]},
    {"name": "currency$subexpression$1$string$40", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$40"]},
    {"name": "currency$subexpression$1$string$41", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$41"]},
    {"name": "currency$subexpression$1$string$42", "symbols": [{"literal":"P"}, {"literal":"L"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$42"]},
    {"name": "currency$subexpression$1$string$43", "symbols": [{"literal":"z"}, {"literal":"ł"}, {"literal":"o"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$43"]},
    {"name": "currency$subexpression$1$string$44", "symbols": [{"literal":"z"}, {"literal":"ł"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$44"]},
    {"name": "currency$subexpression$1$string$45", "symbols": [{"literal":"z"}, {"literal":"ł"}, {"literal":"o"}, {"literal":"t"}, {"literal":"y"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$45"]},
    {"name": "currency$subexpression$1$string$46", "symbols": [{"literal":"z"}, {"literal":"ł"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$46"]},
    {"name": "currency$subexpression$1$string$47", "symbols": [{"literal":"Z"}, {"literal":"ł"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$47"]},
    {"name": "currency$subexpression$1$string$48", "symbols": [{"literal":"E"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$48"]},
    {"name": "currency$subexpression$1$string$49", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$49"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"€"}]},
    {"name": "currency$subexpression$1$string$50", "symbols": [{"literal":"R"}, {"literal":"O"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$50"]},
    {"name": "currency$subexpression$1$string$51", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"j"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$51"]},
    {"name": "currency$subexpression$1$string$52", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"j"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$52"]},
    {"name": "currency$subexpression$1$string$53", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$53"]},
    {"name": "currency$subexpression$1$string$54", "symbols": [{"literal":"R"}, {"literal":"U"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$54"]},
    {"name": "currency$subexpression$1$string$55", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"b"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$55"]},
    {"name": "currency$subexpression$1$string$56", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$56"]},
    {"name": "currency$subexpression$1$string$57", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$57"]},
    {"name": "currency$subexpression$1$string$58", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$58"]},
    {"name": "currency$subexpression$1$string$59", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"z"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"z"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$59"]},
    {"name": "currency$subexpression$1$string$60", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"z"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"z"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$60"]},
    {"name": "currency$subexpression$1$string$61", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"s"}, {"literal":"z"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"z"}, {"literal":"k"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$61"]},
    {"name": "currency$subexpression$1$string$62", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$62"]},
    {"name": "currency$subexpression$1$string$63", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$63"]},
    {"name": "currency$subexpression$1$string$64", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$64"]},
    {"name": "currency$subexpression$1$string$65", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$65"]},
    {"name": "currency$subexpression$1$string$66", "symbols": [{"literal":"U"}, {"literal":"A"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$66"]},
    {"name": "currency$subexpression$1$string$67", "symbols": [{"literal":"h"}, {"literal":"r"}, {"literal":"y"}, {"literal":"w"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$67"]},
    {"name": "currency$subexpression$1$string$68", "symbols": [{"literal":"h"}, {"literal":"r"}, {"literal":"y"}, {"literal":"w"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$68"]},
    {"name": "currency$subexpression$1$string$69", "symbols": [{"literal":"h"}, {"literal":"r"}, {"literal":"y"}, {"literal":"w"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$69"]},
    {"name": "currency$subexpression$1$string$70", "symbols": [{"literal":"G"}, {"literal":"B"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$70"]},
    {"name": "currency$subexpression$1$string$71", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$71"]},
    {"name": "currency$subexpression$1$string$72", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$72"]},
    {"name": "currency$subexpression$1$string$73", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$73"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"£"}]},
    {"name": "currency$subexpression$1$string$74", "symbols": [{"literal":"U"}, {"literal":"S"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$74"]},
    {"name": "currency$subexpression$1$string$75", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$75"]},
    {"name": "currency$subexpression$1$string$76", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$76"]},
    {"name": "currency$subexpression$1$string$77", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"ó"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "currency$subexpression$1", "symbols": ["currency$subexpression$1$string$77"]},
    {"name": "currency$subexpression$1", "symbols": [{"literal":"$"}]},
    {"name": "currency", "symbols": ["currency$subexpression$1"], "postprocess": function(d) {return {token:"currency", value:d[0][0]}}},
    {"name": "string$subexpression$1$string$1", "symbols": [{"literal":"k"}, {"literal":"w"}, {"literal":"o"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "string$subexpression$1", "symbols": ["string$subexpression$1$string$1"]},
    {"name": "string$subexpression$1$string$2", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "string$subexpression$1", "symbols": ["string$subexpression$1$string$2"]},
    {"name": "string$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "string$subexpression$1", "symbols": ["string$subexpression$1$string$3"]},
    {"name": "string$subexpression$1$string$4", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"o"}, {"literal":"ś"}, {"literal":"ć"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "string$subexpression$1", "symbols": ["string$subexpression$1$string$4"]},
    {"name": "string$subexpression$1$string$5", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"t"}, {"literal":"ó"}, {"literal":"w"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "string$subexpression$1", "symbols": ["string$subexpression$1$string$5"]},
    {"name": "string", "symbols": ["string$subexpression$1"], "postprocess": function(d) {return {token:"string", value:d[0][0]}}},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) { return null }},
    {"name": "formatOne$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$ebnf$2", "symbols": ["string"], "postprocess": id},
    {"name": "formatOne$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$ebnf$3", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$subexpression$1", "symbols": ["float"]},
    {"name": "formatOne$subexpression$1", "symbols": ["int"]},
    {"name": "formatOne$ebnf$4", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$ebnf$5", "symbols": ["scalars"], "postprocess": id},
    {"name": "formatOne$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$ebnf$6", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$subexpression$2", "symbols": ["currency"]},
    {"name": "formatOne$subexpression$2$subexpression$1$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$subexpression$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$subexpression$2$subexpression$1$ebnf$2", "symbols": ["_"], "postprocess": id},
    {"name": "formatOne$subexpression$2$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatOne$subexpression$2$subexpression$1", "symbols": ["currency", "formatOne$subexpression$2$subexpression$1$ebnf$1", "scalars", "formatOne$subexpression$2$subexpression$1$ebnf$2"]},
    {"name": "formatOne$subexpression$2", "symbols": ["formatOne$subexpression$2$subexpression$1"]},
    {"name": "formatOne", "symbols": ["formatOne$ebnf$1", "formatOne$ebnf$2", "formatOne$ebnf$3", "formatOne$subexpression$1", "formatOne$ebnf$4", "formatOne$ebnf$5", "formatOne$ebnf$6", "formatOne$subexpression$2"]},
    {"name": "formatTwo$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "formatTwo$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo$ebnf$2", "symbols": ["string"], "postprocess": id},
    {"name": "formatTwo$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo$ebnf$3", "symbols": ["_"], "postprocess": id},
    {"name": "formatTwo$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo$subexpression$1", "symbols": ["scalars"]},
    {"name": "formatTwo$subexpression$1", "symbols": ["time"]},
    {"name": "formatTwo$subexpression$1", "symbols": ["currency"]},
    {"name": "formatTwo$ebnf$4", "symbols": ["_"], "postprocess": id},
    {"name": "formatTwo$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo$subexpression$2", "symbols": ["currency"]},
    {"name": "formatTwo$subexpression$2", "symbols": ["float"]},
    {"name": "formatTwo$subexpression$2", "symbols": ["int"]},
    {"name": "formatTwo$ebnf$5", "symbols": ["_"], "postprocess": id},
    {"name": "formatTwo$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo$subexpression$3", "symbols": ["float"]},
    {"name": "formatTwo$subexpression$3", "symbols": ["int"]},
    {"name": "formatTwo$subexpression$3", "symbols": ["scalars"]},
    {"name": "formatTwo$subexpression$3", "symbols": ["time"]},
    {"name": "formatTwo$ebnf$6", "symbols": ["_"], "postprocess": id},
    {"name": "formatTwo$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatTwo", "symbols": ["formatTwo$ebnf$1", "formatTwo$ebnf$2", "formatTwo$ebnf$3", "formatTwo$subexpression$1", "formatTwo$ebnf$4", "formatTwo$subexpression$2", "formatTwo$ebnf$5", "formatTwo$subexpression$3", "formatTwo$ebnf$6"]},
    {"name": "formatThree$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "formatThree$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$ebnf$2", "symbols": ["string"], "postprocess": id},
    {"name": "formatThree$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$ebnf$3", "symbols": ["_"], "postprocess": id},
    {"name": "formatThree$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$subexpression$1", "symbols": ["scalars"]},
    {"name": "formatThree$subexpression$1", "symbols": ["time"]},
    {"name": "formatThree$ebnf$4", "symbols": ["_"], "postprocess": id},
    {"name": "formatThree$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$subexpression$2", "symbols": ["currency"]},
    {"name": "formatThree$subexpression$2$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "formatThree$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$subexpression$2$subexpression$1", "symbols": ["float"]},
    {"name": "formatThree$subexpression$2$subexpression$1", "symbols": ["int"]},
    {"name": "formatThree$subexpression$2$ebnf$2", "symbols": ["_"], "postprocess": id},
    {"name": "formatThree$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "formatThree$subexpression$2", "symbols": ["currency", "formatThree$subexpression$2$ebnf$1", "formatThree$subexpression$2$subexpression$1", "formatThree$subexpression$2$ebnf$2"]},
    {"name": "formatThree", "symbols": ["formatThree$ebnf$1", "formatThree$ebnf$2", "formatThree$ebnf$3", "formatThree$subexpression$1", "formatThree$ebnf$4", "formatThree$subexpression$2"]},
    {"name": "noCurrency$ebnf$1", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency$ebnf$2", "symbols": ["string"], "postprocess": id},
    {"name": "noCurrency$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency$ebnf$3", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency$subexpression$1", "symbols": ["float"]},
    {"name": "noCurrency$subexpression$1", "symbols": ["int"]},
    {"name": "noCurrency$ebnf$4", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency$subexpression$2", "symbols": ["scalars"]},
    {"name": "noCurrency$subexpression$2", "symbols": ["time"]},
    {"name": "noCurrency$ebnf$5", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency", "symbols": ["noCurrency$ebnf$1", "noCurrency$ebnf$2", "noCurrency$ebnf$3", "noCurrency$subexpression$1", "noCurrency$ebnf$4", "noCurrency$subexpression$2", "noCurrency$ebnf$5"]},
    {"name": "noCurrency$subexpression$3", "symbols": ["scalars"]},
    {"name": "noCurrency$subexpression$3", "symbols": ["time"]},
    {"name": "noCurrency$ebnf$6", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency$subexpression$4", "symbols": ["float"]},
    {"name": "noCurrency$subexpression$4", "symbols": ["int"]},
    {"name": "noCurrency$ebnf$7", "symbols": ["_"], "postprocess": id},
    {"name": "noCurrency$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noCurrency", "symbols": ["noCurrency$subexpression$3", "noCurrency$ebnf$6", "noCurrency$subexpression$4", "noCurrency$ebnf$7"]}
]
  , ParserStart: "Main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
